version: '3'
services:
  u-boot-build:
    image: docker.io/pergamos/bsp-builder:latest
    volumes:
      - ${BUILD_PATH}/tmp/${MACHINE}/u-boot:/source
      - ${ORIGIN_PATH}:/assets
    command:
      make
        CROSS_COMPILE=${COMPILER}
        -j${JOBS}

  u-boot-config:
    image: docker.io/pergamos/bsp-builder:latest
    user: ${GUSER_ID}:${GGROUP_ID}
    volumes:
      - ${BUILD_PATH}/tmp/${MACHINE}/u-boot:/source
      - ${ORIGIN_PATH}:/assets
    command:
      make
        CROSS_COMPILE=${COMPILER}
        ${MACHINE}_defconfig

  u-boot-mkimage:
    image: docker.io/pergamos/bsp-builder:latest
    user: ${GUSER_ID}:${GGROUP_ID}
    volumes:
      - ${BUILD_PATH}/tmp/${MACHINE}/u-boot:/source
      - ${ORIGIN_PATH}:/assets
    command:
      mkimage -A ${MIN_ARCH}
        -O linux
        -T script
        -C none
        -n /assets/${MACHINE}/boot.src
        -d /assets/${MACHINE}/boot.src
        /source/boot.scr.uimg
