#!/bin/bash

set -e

# run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 69
fi

# update
apt-get update

# make sure to have parcial dependencies
apt-get install -y \
    unzip \
    curl \
    wget \
    git \
    sudo \
    parted \
    dosfstools \
    binutils \
    whois \
    jq

# install podman
apt-get install -y --no-install-recommends podman-compose

# install bun
curl -fsSL https://bun.sh/install | bash

if [ ! -L /opt/bun ]; then
    ln -s /root/.bun/ /opt/bun
fi

# add it to the path
echo "export PATH=$PATH:/opt/bun/bin" >>/etc/profile
