#!/bin/bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 69
fi

# update
apt-get update

# make sure to have parcial dependencies
apt-get install -y \
    unzip \
    curl \
    wget \
    git \
    sudo \
    parted \
    dosfstools \
    binutils \
    whois \
    jq \
    locales \
    bash-completion

# install podman
apt-get install -y --no-install-recommends podman-compose

# install deno
curl -fsSL https://deno.land/install.sh | sh -s -- -y

if [ ! -L /opt/deno ]; then
    ln -s /root/.deno/ /opt/deno
fi

# add it to the path
echo "export PATH=$PATH:/opt/deno/bin" >>/etc/profile

# install bash completion for bitcook
install -Dm644 "${SCRIPT_DIR}/bitcook-completion" \
    /usr/share/bash-completion/completions/bitcook
