version: '3'
services:
  linux-build:
    image: docker.io/pergamos/bsp-builder:latest
    volumes:
      - ${BUILD_PATH}/tmp/${MACHINE}/linux:/source
      - ${ORIGIN_PATH}:/assets
    command:
      make
        ARCH=${LINUX_ARCH}
        CROSS_COMPILE=${COMPILER}
        ${IMAGE_TYPE}
        -j${JOBS}

  linux-modules:
    image: docker.io/pergamos/bsp-builder:latest
    user: ${GUSER_ID}:${GGROUP_ID}
    volumes:
      - ${BUILD_PATH}/tmp/${MACHINE}/linux:/source
      - ${ORIGIN_PATH}:/assets
    command:
      make
        ARCH=${LINUX_ARCH}
        CROSS_COMPILE=${COMPILER}
        modules
        ${MACHINE}_defconfig
        -j${JOBS}

  linux-install-modules:
    image: docker.io/pergamos/bsp-builder:latest
    user: root
    volumes:
      - ${BUILD_PATH}/tmp/${MACHINE}/linux:/source
      - ${ORIGIN_PATH}:/assets
      - ${IMAGE_MNT_ROOT}:/rootfs
    command:
      make
        ARCH=${LINUX_ARCH}
        CROSS_COMPILE=${COMPILER}
        INSTALL_MOD_PATH=/rootfs
        modules_install

  linux-install-headers:
    image: docker.io/pergamos/bsp-builder:latest
    user: root
    volumes:
      - ${BUILD_PATH}/tmp/${MACHINE}/linux:/source
      - ${ORIGIN_PATH}:/assets
      - ${BUILD_PATH}/tmp/${MACHINE}/rootfs:/rootfs
    command:
      make
        ARCH=${LINUX_ARCH}
        CROSS_COMPILE=${COMPILER}
        INSTALL_MOD_PATH=/rootfs
        headers_install

  linux-dtb:
    image: docker.io/pergamos/bsp-builder:latest
    user: ${GUSER_ID}:${GGROUP_ID}
    volumes:
      - ${BUILD_PATH}/tmp/${MACHINE}/linux:/source
      - ${ORIGIN_PATH}:/assets
    command:
      make
        ARCH=${LINUX_ARCH}
        CROSS_COMPILE=${COMPILER}
        dtbs
        ${MACHINE}_defconfig
        -j${JOBS}

  linux-config:
    image: docker.io/pergamos/bsp-builder:latest
    user: ${GUSER_ID}:${GGROUP_ID}
    volumes:
      - ${BUILD_PATH}/tmp/${MACHINE}/linux:/source
      - ${ORIGIN_PATH}:/assets
    command:
      make
        ARCH=${LINUX_ARCH}
        CROSS_COMPILE=${COMPILER}
        ${MACHINE}_defconfig
