

FROM debian:bookworm


COPY . /gaia

# setup
RUN chmod +x /gaia/scripts/utils/deps && \
    cd /gaia/scripts/utils && \
    ./deps

# workspace will be mounted
WORKDIR /workspace

# create the gaia user
RUN useradd -m -s /bin/bash gaia && \
    echo "gaia ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/gaia && \
    chown -R gaia:gaia /root/.bun/ && \
    chmod -R 775 /root && \
    cd /gaia && \
    /root/.bun/bin/bun install

USER gaia

CMD [ "/gaia/scripts/bitcook/gaia.ts", "--help" ]
