

FROM debian:bookworm


COPY . /gaia

# setup
RUN chmod +x /gaia/scripts/utils/deps && \
    cd /gaia/scripts/utils && \
    ./deps

# workspace will be mounted
WORKDIR __pwd__

# create the gaia user
RUN useradd -m -u __uid__ -s /bin/bash gaia && \
    echo "gaia ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/gaia && \
    chown -R gaia:gaia /root/.bun/ && \
    chmod -R 775 /root && \
    cd /gaia && \
    /root/.bun/bin/bun install && \
    ln -s /root/.bun/bin/bun /usr/bin/bun && \
    echo "export GUSER_ID=__uid__" >> /etc/profile && \
    echo "export GGROUP_ID=__gid__" >> /etc/profile

USER gaia

CMD [ "/gaia/scripts/bitcook/gaia.ts", "--help" ]
