services:
  build:
    build:
      context: ..
      dockerfile: .devcontainer/Containerfile
    volumes:
      - __pwd__:__pwd__
    image: pergamos/gaia-workspace-dev:latest

  repo:
    volumes:
      - __pwd__:__pwd__
    image: pergamos/gaia-workspace-dev:latest
    command: "__pwd__/gaia/scripts/utils/repo.ts"

  dev:
    volumes:
      - __pwd__:__pwd__
      - /etc/subuid:/etc/subuid:ro
      - /etc/subgid:/etc/subgid:ro
    privileged: true
    network_mode: host
    cgroup: host
    image: pergamos/gaia-workspace-dev:latest
    command: "bash"
