services:
  build:
    build:
      context: ..
      dockerfile: .devcontainer/Containerfile
    volumes:
      - ../../:/workspace
    image: pergamos/gaia-workspace-dev:latest

  repo:
    volumes:
      - ../../:/workspace
    image: pergamos/gaia-workspace-dev:latest
    command: "/workspace/gaia/scripts/utils/repo.ts"

  dev:
    volumes:
      - ../../:/workspace
    image: pergamos/gaia-workspace-dev:latest
    command: "bash"
