#!/bin/bash

set -e

# check if docker is installed
if ! command -v docker &>/dev/null; then
    echo "Docker could not be found"
    exit
fi

# check if docker compose plugin is installed
# not docker-compose the plugin compose
if ! docker --help | grep -q compose; then
    echo "Docker compose plugin could not be found"
    exit
fi

# get the user id
USER_ID=$(id -u)
# get the group id
GROUP_ID=$(id -g)
# get the docker group id
DGROUP_ID=$(getent group docker | cut -d: -f3)

# sed for change the __pwd__ to the current absolute path
# this way we will not have issues with docker in docker mounts
sed -i "s#__pwd__#$(pwd)#g" ./gaia/.devcontainer/docker-compose.yml
sed -i "s#__pwd__#$(pwd)#g" ./gaia/.devcontainer/Containerfile
sed -i "s#__pwd__#$(pwd)#g" ./gaia/.devcontainer/devcontainer.json
sed -i "s#__pwd__#$(pwd)#g" ./gaia/.vscode/settings.json
sed -i "s#__pwd__#$(pwd)#g" ./gaia/scripts/utils/repo.ts

# sed for change the __uid__ to the current user id
sed -i "s#__uid__#$USER_ID#g" ./gaia/.devcontainer/docker-compose.yml
sed -i "s#__uid__#$USER_ID#g" ./gaia/.devcontainer/Containerfile
sed -i "s#__uid__#$USER_ID#g" ./gaia/.devcontainer/devcontainer.json
sed -i "s#__uid__#$USER_ID#g" ./gaia/.vscode/settings.json
sed -i "s#__uid__#$USER_ID#g" ./gaia/scripts/utils/repo.ts

# sed for change the __gid__ to the current group id
sed -i "s#__gid__#$GROUP_ID#g" ./gaia/.devcontainer/docker-compose.yml
sed -i "s#__gid__#$GROUP_ID#g" ./gaia/.devcontainer/Containerfile
sed -i "s#__gid__#$GROUP_ID#g" ./gaia/.devcontainer/devcontainer.json
sed -i "s#__gid__#$GROUP_ID#g" ./gaia/.vscode/settings.json
sed -i "s#__gid__#$GROUP_ID#g" ./gaia/scripts/utils/repo.ts

# sed for change the __dgid__ to the current docker group id
sed -i "s#__dgid__#$DGROUP_ID#g" ./gaia/.devcontainer/docker-compose.yml
sed -i "s#__dgid__#$DGROUP_ID#g" ./gaia/.devcontainer/Containerfile
sed -i "s#__dgid__#$DGROUP_ID#g" ./gaia/.devcontainer/devcontainer.json
sed -i "s#__dgid__#$DGROUP_ID#g" ./gaia/.vscode/settings.json
sed -i "s#__dgid__#$DGROUP_ID#g" ./gaia/scripts/utils/repo.ts

# run the build of the devcontainer
docker compose -f ./gaia/.devcontainer/docker-compose.yml build

# run the repo
docker compose -f ./gaia/.devcontainer/docker-compose.yml run --rm repo
